name: Advertisingfranchise.info
favicon: null
layout_spectrum: 0.9225752062629908
typography_spectrum: 0.900833546416834
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.27514160331338644
  lightness: 0.863833273993805
  saturation: 0.9408009005710483
  rhythmicContrast: 0.787693346850574
purpose: []
